### ISSUE TITLE
'update_strategy' variable has wrong default value.

### ISSUE THREAD

**Issue by ashayh** [GoogleCloudPlatform/terraform-google-managed-instance-group#13]
When using the [terraform-k8s](https://github.com/GoogleCloudPlatform/terraform-google-k8s-gce) module, I get this error:

`Error: module.k8s.module.default-pool-mig.google_compute_region_instance_group_manager.default: expected update_strategy to be one of [NONE ROLLING_UPDATE], got RESTART`

**Comment by danisla** [comment]
Fixed in: https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/commit/b25c1feaec3511f5d8d613cf511f2a4a8d3f07bb
