### ISSUE TITLE
Add support for Terraform 0.12

### ISSUE THREAD

**Issue by ivankorn** [GoogleCloudPlatform/terraform-google-managed-instance-group#42]
Please, note: 
0.12 support for [`managed_instance_group example`](https://github.com/terraform-google-modules/terraform-google-container-vm/tree/master/examples/managed_instance_group) depends on this.
Module to be updated once this task is done. 
Linked: 
- [`module container-vm`](https://github.com/terraform-google-modules/terraform-google-container-vm/issues/28)
- [`terraform-google-lb-http`](https://github.com/GoogleCloudPlatform/terraform-google-lb-http/issues/51)

**Comment by morgante** [comment]
This module will be deprecated, so we will not migrate it to v0.12.

Please replace usage with this module: https://github.com/terraform-google-modules/terraform-google-vm/tree/master/modules/mig
