### ISSUE TITLE
 Error: Unsupported argument

### ISSUE THREAD

**Issue by jimisan** [GoogleCloudPlatform/terraform-google-managed-instance-group#45]
terraform apply -auto-approve -target=module.lbroup-fd61bad/mai

Error: Incorrect attribute value type

  on .terraform/modules/mig/GoogleCloudPlatform-terraform-google-managed-instance-group-fd61bad/main.tf line 26, in resource "google_compute_instance_template" "default":
  26:   tags = ["${concat(list("allow-ssh"), var.target_tags)}"]

Inappropriate value for attribute "tags": element 0: string required.

Error: Unsupported argument

  on .terraform/modules/mig/GoogleCloudPlatform-terraform-google-managed-instance-group-fd61bad/main.tf line 33, in resource "google_compute_instance_template" "default":
  33:     access_config      = ["${var.access_config}"]

An argument named "access_config" is not expected here. Did you mean to define
a block of type "access_config"?

Error: Incorrect attribute value type

  on .terraform/modules/mig/GoogleCloudPlatform-terraform-google-managed-instance-group-fd61bad/main.tf line 52, in resource "google_compute_instance_template" "default":
  52:     scopes = ["${var.service_account_scopes}"]

Inappropriate value for attribute "scopes": element 0: string required.

**Comment by morgante** [comment]
Can you share your Terraform config?

**Comment by jimisan** [comment]
sure, I'll try asap.

**Comment by cyb3ralbert** [comment]
https://github.com/jimisan/terraform, @morgante. here you are!

**Comment by morgante** [comment]
@jimisan This module is no longer maintained, so I'd suggest you switch to https://github.com/terraform-google-modules/terraform-google-vm/tree/master/modules/mig.

**Comment by cyb3ralbert** [comment]
thank you.
